SELECT
	STUDENTS.ID,
	STUDENTS.STATE_STUDENTNUMBER,
	STUDENTS.STUDENT_NUMBER,
	STUDENTS.FIRST_NAME,
	STUDENTS.LAST_NAME,
	regexp_substr (students.street,'^[0-9]*') AS "unitNumber",
	trim(regexp_substr (students.street,'(\D).[^,]+')) AS "streetAddress",
	trim(substr(regexp_substr (students.street,'(\,)(.*)'),2)) AS "aptNumber",
	STUDENTS.CITY,
	STUDENTS.ZIP,
	STUDENTS.SCHOOLID,
	STUDENTS.MAILING_STREET,
	STUDENTS.MAILING_CITY,
	STUDENTS.MAILING_ZIP,
	students.GRADE_LEVEL,
	STUDENTS.GENDER,
	--STUDENTS.ENROLL_STATUS,
	S_MI_STU_GC_X.FLAGSPECED
	


FROM STUDENTS
	JOIN S_MI_STU_GC_X ON STUDENTS.DCID = S_MI_STU_GC_X.STUDENTSDCID

WHERE
	STUDENTS.ENROLL_STATUS IN (-1,0)
